version: '3'

tasks:
  default:
    alias: bootstrap
    cmds:
      - task: install-docker
      - task: install-utils
      - task: stow-bash
      - task: stow-config

  install-homebrew:
    cmds:
      - curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    status:
      - command -v brew

  install-docker:
    cmds:
      - bash scripts/install-docker.sh
    status:
      - command -v docker

  install-tmux:
    cmds:
      - sudo apt-get install libevent-dev ncurses-dev build-essential bison pkg-config
      - mise install tmux
    status:
      - command -v tmux

  install-stow:
    deps: [install-homebrew]
    cmds:
      - ./scripts/brew-install.sh stow
    env:
    status:
      - command -v stow

  install-utils:
    deps: [install-homebrew]
    cmds:
      - ./scripts/brew-install.sh lazygit
      - ./scripts/brew-install.sh lazydocker
      - ./scripts/brew-install.sh unzip
    status:
      - command -v lazygit
      - command -v lazydocker

  stow-bash:
    cmds:
      - /home/linuxbrew/.linuxbrew/bin/stow --dotfiles --adopt bash 

  stow-config:
    deps: [install-stow, install-tmux]
    cmds:
      - /home/linuxbrew/.linuxbrew/bin/stow --dotfiles nvim
      - /home/linuxbrew/.linuxbrew/bin/stow --dotfiles tmux
      - /home/linuxbrew/.linuxbrew/bin/stow --dotfiles mise
      - /home/linuxbrew/.linuxbrew/bin/stow --dotfiles stylua
      - /home/linuxbrew/.linuxbrew/bin/stow tools
      - task: install-tpm

  install-tpm:
    deps: [install-tmux]
    cmds:
      - git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
      - bash ~/.config/tmux/plugins/tpm/bin/install_plugins
    status:
      - test -d tmux/dot-config/tmux/plugins/tpm
