name = "terminal-tools"
name_pretty = "TUIs"
icon = "utilities-terminal"
terminal = true
action = "%VALUE%"

[[entries]]
text = "btop"
value = "btop"

[[entries]]
text = "impala"
keywords = ["network", "wifi", "ethernet", "connection"]
subtext = "manage network connections"
icon = "network-wired"
value = "impala"

[[entries]]
text = "bluetui"
keywords = ["bluetooth", "audio", "connection"]
subtext = "manage bluetooth connections"
icon = "audio-headphones"
value = "bluetui"

[[entries]]
text = "htop"
keywords = ["process", "monitor", "cpu", "memory"]
icon = "utilities-system-monitor"
value = "htop"

[[entries]]
text = "systemctl-tui"
keywords = ["system", "daemons"]
value = "systemctl-tui"
